name: Deploy Platformatic application to the cloud
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs:
  build_and_deploy:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout application project repository
        uses: actions/checkout@v3
      - name: npm install --omit=dev
        run: npm install --omit=dev
      - name: Deploy project
        id: deploy-project
        uses: platformatic/onestep@risks
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          platformatic_workspace_id: 2cf1f677-4928-4a26-b176-459895523f46
          platformatic_workspace_key: af066d3c842a4c78ac28a0f86b95c926
          platformatic_config_path: ./platformatic.runtime.json
        env:
          PLT_SERVER_HOSTNAME: 127.0.0.1
          PORT: 3042
          PLT_SERVER_LOGGER_LEVEL: info
          DEPLOY_SERVICE_HOST: https://plt-development-deploy-service.fly.dev

    outputs:
      deployment_id: ${{ steps.deploy-project.outputs.deployment_id }}
  calculate_risk:
    needs: build_and_deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Calculate risk
        uses: platformatic/onestep/actions/calculate-risk@risks
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          platformatic_workspace_id: 2cf1f677-4928-4a26-b176-459895523f46
          platformatic_workspace_key: af066d3c842a4c78ac28a0f86b95c926
          platformatic_deployment_id: ${{ needs.build_and_deploy.outputs.deployment_id }}
        env:
          DEPLOY_SERVICE_HOST: https://plt-development-deploy-service.fly.dev